version: '3.9'
services:
  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - 'redis'
    env_file:
      - ./.env
  web:
    build: .
    ports:
      - '80:3000'
    command:
      - /bin/bash
      - -c
      - |
        rm -f tmp/pids/server.pid
        bundle exec rake db:migrate 2>/dev/null || bundle exec rake db:create db:migrate
        bundle exec rake db:seed
        RAILS_ENV=production bundle exec rake assets:precompile
        RAILS_ENV=$RAILS_ENV bundle exec rails s -b 0.0.0.0 -p 3000
    depends_on:
      - 'redis'
    env_file:
      - ./.env
  redis:
    image: redis:latest
    command: redis-server
